'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
    async up(queryInterface, Sequelize) {
        await queryInterface.bulkInsert('book', [
            {
                isbn: "391379721",
                title: "Sunrise: A Song of Two Humans",
                author: "Jammal Morrison",
                publisher: "Devshare",
                year: 2001,
                amount: 206,
                category_id: 1,
                bookshelf_id: 2,
                created_at: Sequelize.fn('now'),
                updated_at: Sequelize.fn('now'),
            },
            {
                isbn: "161611989",
                title: "Funeral Parade of Roses (Bara no sôretsu)",
                author: "Baxy Filinkov",
                publisher: "Kanoodle",
                year: 1999,
                amount: 63,
                category_id: 1,
                bookshelf_id: 2,
                created_at: Sequelize.fn('now'),
                updated_at: Sequelize.fn('now'),
            },
            {
                isbn: "236407355",
                title: "All American Chump",
                author: "Ericha Rosson",
                publisher: "Omba",
                year: 2000,
                amount: 196,
                category_id: 1,
                bookshelf_id: 2,
                created_at: Sequelize.fn('now'),
                updated_at: Sequelize.fn('now'),
            },
            {
                isbn: "277718506",
                title: "Crime Spree",
                author: "Janis Trehearn",
                publisher: "Meejo",
                year: 1994,
                amount: 76,
                category_id: 1,
                bookshelf_id: 2,
                created_at: Sequelize.fn('now'),
                updated_at: Sequelize.fn('now'),
            },
            {
                isbn: "119745812",
                title: "Incredible Journey, The",
                author: "Reinhard Pickaver",
                publisher: "Camido",
                year: 2006,
                amount: 253,
                category_id: 1,
                bookshelf_id: 2,
                created_at: Sequelize.fn('now'),
                updated_at: Sequelize.fn('now'),
            },
            {
                isbn: "624969433",
                title: "Homicide",
                author: "Hardy Dukes",
                publisher: "Jaxworks",
                year: 2010,
                amount: 67,
                category_id: 1,
                bookshelf_id: 2,
                created_at: Sequelize.fn('now'),
                updated_at: Sequelize.fn('now'),
            },
            {
                isbn: "625976166",
                title: "Ju-on: Black Ghost",
                author: "Fern Andrusov",
                publisher: "Mudo",
                year: 1998,
                amount: 63,
                category_id: 1,
                bookshelf_id: 2,
                created_at: Sequelize.fn('now'),
                updated_at: Sequelize.fn('now'),
            },
            {
                isbn: "547669720",
                title: "Blade of the Ripper",
                author: "Heriberto Elderbrant",
                publisher: "Devcast",
                year: 2006,
                amount: 223,
                category_id: 1,
                bookshelf_id: 2,
                created_at: Sequelize.fn('now'),
                updated_at: Sequelize.fn('now'),
            },
            {
                isbn: "338636306",
                title: "Good Job:  Stories of the FDNY, A",
                author: "Hadrian Schoroder",
                publisher: "Janyx",
                year: 2006,
                amount: 240,
                category_id: 1,
                bookshelf_id: 2,
                created_at: Sequelize.fn('now'),
                updated_at: Sequelize.fn('now'),
            },
            {
                isbn: "321586825",
                title: "Northern Soul",
                author: "Cole Nowlan",
                publisher: "Yacero",
                year: 1992,
                amount: 349,
                category_id: 1,
                bookshelf_id: 2,
                created_at: Sequelize.fn('now'),
                updated_at: Sequelize.fn('now'),
            },
            {
                isbn: "239055461",
                title: "Two Weeks in September",
                author: "Stacia Peeke-Vout",
                publisher: "Yakitri",
                year: 2007,
                amount: 199,
                category_id: 1,
                bookshelf_id: 2,
                created_at: Sequelize.fn('now'),
                updated_at: Sequelize.fn('now'),
            },
            {
                isbn: "456499753",
                title: "Nightmare on Elm Street 3: Dream Warriors, A",
                author: "Erina Rosita",
                publisher: "Agivu",
                year: 2005,
                amount: 281,
                category_id: 1,
                bookshelf_id: 2,
                created_at: Sequelize.fn('now'),
                updated_at: Sequelize.fn('now'),
            },
            {
                isbn: "787654782",
                title: "Canned Dreams (Säilöttyjä unelmia)",
                author: "Aviva Bourthoumieux",
                publisher: "Thoughtbeat",
                year: 1987,
                amount: 314,
                category_id: 1,
                bookshelf_id: 2,
                created_at: Sequelize.fn('now'),
                updated_at: Sequelize.fn('now'),
            },
            {
                isbn: "892048258",
                title: "Witches, The (aka Devil's Own, The)",
                author: "Ebba Aronin",
                publisher: "Camimbo",
                year: 1998,
                amount: 169,
                category_id: 1,
                bookshelf_id: 2,
                created_at: Sequelize.fn('now'),
                updated_at: Sequelize.fn('now'),
            },
            {
                isbn: "118153556",
                title: "Monster House",
                author: "Raimondo Boutellier",
                publisher: "Abatz",
                year: 1996,
                amount: 151,
                category_id: 2,
                bookshelf_id: 2,
                created_at: Sequelize.fn('now'),
                updated_at: Sequelize.fn('now'),
            },
            {
                isbn: "118285213",
                title: "Lakota Woman: Siege at Wounded Knee",
                author: "Corella Costigan",
                publisher: "Mynte",
                year: 2003,
                amount: 180,
                category_id: 2,
                bookshelf_id: 2,
                created_at: Sequelize.fn('now'),
                updated_at: Sequelize.fn('now'),
            },
            {
                isbn: "693914455",
                title: "Flamenco (de Carlos Saura)",
                author: "Ainsley Cromley",
                publisher: "Yombu",
                year: 1988,
                amount: 311,
                category_id: 1,
                bookshelf_id: 2,
                created_at: Sequelize.fn('now'),
                updated_at: Sequelize.fn('now'),
            },
            {
                isbn: "533927978",
                title: "Jackass 2.5",
                author: "Mavis Southcoat",
                publisher: "Oloo",
                year: 2010,
                amount: 60,
                category_id: 1,
                bookshelf_id: 2,
                created_at: Sequelize.fn('now'),
                updated_at: Sequelize.fn('now'),
            },
            {
                isbn: "658660821",
                title: "Joyful Noise",
                author: "Anatola Quilty",
                publisher: "Gabspot",
                year: 2008,
                amount: 290,
                category_id: 1,
                bookshelf_id: 2,
                created_at: Sequelize.fn('now'),
                updated_at: Sequelize.fn('now'),
            },
            {
                isbn: "110604274",
                title: "Mystery (Fu cheng mi shi)",
                author: "Tamiko Vaar",
                publisher: "Quatz",
                year: 2012,
                amount: 189,
                category_id: 2,
                bookshelf_id: 2,
                created_at: Sequelize.fn('now'),
                updated_at: Sequelize.fn('now'),
            }
        ], {});
    },

    async down(queryInterface, Sequelize) {
        await queryInterface.bulkDelete('book', null, {});
    }
};
